### PR TITLE
canonicalize() handle /./ in path

### PR DESCRIPTION
**Pull request by mckellyln**
@Andersbakken take a look.  I had /dir1/dir2/./../../dir3 paths that were not being canonicalized properly.

### CODE REVIEW

**Comment by cslux** [comment]
We should add a cppunit test for this!

**Comment by cslux** [comment]
@mckellyln I added a test PathTestSuite::testCanonicalize() which fails right now.

**Comment by mckellyln** [comment]
@cslux ok great and thank you. Can you check if it passes with my PR ?  I will look into how to do that.

**Comment by cslux** [comment]
@mckellyln Yep it passes! However I discovered another issue. The trailing '/' gets not removed, but should.

**Pull request merged**
